### ISSUE TITLE
broken links in blog

### ISSUE THREAD

**Issue by msztolcman** [j-bennet/wharfee.com#4]
For example, on blog page: http://wharfee.com/meet-wharfee.html there are broken links. One of them is 'Blog' category, points to non-existing http://wharfee.com/category/Blog.html, or author Iryna Cherniavska points to broken http://wharfee.com/author/Iryna%20Cherniavska.html. Archive is also broken :)

**Comment by j-bennet** [comment]
@msztolcman Thanks for pointing this out! Fixed now.
